### PR TITLE
Add vim file type support using vint

### PR DESCRIPTION
**Pull request by KabbAmine**
As the title said.

Note that I'm not a python expert, so please check if the test is ok.

### CODE REVIEW

**Comment by junkblocker** [comment]
Hello, @KabbAmine , you'd want to put them in a subdirectory based module ( e.g. for sh )rather than using a single file as there are other linters for VimL (In fact I already had one in the works). That way more than one linter can be used.

**Comment by KabbAmine** [comment]
@junkblocker Sure.

**Comment by KabbAmine** [comment]
I've fixed the test, squashed all the changes in one commit and force pushed.

**Comment by maralla** [comment]
Can you fix the conflict.

**Comment by KabbAmine** [comment]
@maralla Done

**Pull request merged**
